--Calculate average salary per department
SELECT DEPARTMENT,AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE GROUP BY DEPARTMENT;

--Rank Employee within Each depertment by salary
SELECT EMP_ID,EMP_NAME,DEPARTMENT FROM (
SELECT EMP_ID, 
EMP_NAME, 
DEPARTMENT
,RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) RNK
FROM EMPLOYEE
)ORDER BY DEPARTMENT, RNK DESC;

--Highest paid salary per department
SELECT EMP_ID,EMP_NAME,DEPARTMENT FROM (
SELECT EMP_ID, 
EMP_NAME, 
DEPARTMENT
,RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) RNK
FROM EMPLOYEE
)WHERE RNK = 1;

--salary contribution percentage per department
SELECT DEPARTMENT
,SUM(SALARY) OVER (PARTITION BY DEPARTMENT)/SUM(SALARY) AS DEP_CONTRIBUTION_IN_TOTAL_SAL
FROM EMPLOYEE;

-- Fetch employees from a specific partition (e.g., location)
SELECT
    EMP_ID,
    NAME,
    DEPARTMENT,
    SALARY,
    LOCATION
FROM EMPLOYEES
WHERE LOCATION = 'Bangalore';

